<a href="https://colab.research.google.com/github/HJuliamPR/ColabPython/blob/main/PandasTratamientoManipulaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROBLEMA DE NEGOCIO

Se trata de un algoritmo capaz de analizar las características de una propiedad, como comodidades, tamaño, ocupación del espacio en un periodo determinado- y sugerir al anfitrión un precio a cobrar por tarifas diarias que garantice ganancias en momentos de alta demanda.

# Entendiendo el Problema

In [ ]:
import pandas as pd

In [ ]:
DataHosting = pd.read_json('/content/drive/MyDrive/GoogleColab/datos_hosting.json')
DataInmuebles = pd.read_json('/content/drive/MyDrive/GoogleColab/inmuebles_disponibles.json')

In [ ]:
DataHosting = pd.json_normalize( DataHosting['info_inmuebles'] )
DataHosting.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [ ]:
DataHosting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB

## Datos Numéricos

In [ ]:
ColumnsHosting = list( DataHosting.columns )
ColumnsHosting

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_baños',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

In [ ]:
# Lo que hace es desagregar los valores tipo lista y crear más registros
DataHosting = DataHosting.explode(ColumnsHosting[3:])

In [ ]:
# Lo que hace es volver a contar el índice y aplicar directamente en el DataFrame
DataHosting.reset_index(inplace = True, drop = True)
DataHosting.head(3)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00

In [ ]:
DataHosting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [ ]:
# Biblioteca para trabajar con datos numéricos Aplicar fórmulas matemáticas.
import numpy as np

In [ ]:
# Se le asigna el tipo de variable de la columna a entero
DataHosting['max_hospedes'] = DataHosting['max_hospedes'].astype(np.int64)

In [ ]:
ColumnINT64 = ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']

In [ ]:
DataHosting[ColumnINT64] = DataHosting[ColumnINT64].astype(np.int64)

In [ ]:
# Se le asigna el tipo de variable de la columna a flotante
DataHosting['evaluacion_general'] = DataHosting['evaluacion_general'].astype(np.float64)

In [ ]:
# Método para transformar los datos en la columna indicada.
# Con la función homónima lambda cada uno de los parámetros.
# el método apply solo funciona para una única columna o sea, una serie.
DataHosting['precio'] = DataHosting['precio'].apply(lambda x: x.replace('$','').replace(',','').strip()).astype(np.float64)

In [ ]:
# The applymap method works with dataframes
# DataHosting[['cuota_deposito', 'cuota_limpieza']] = DataHosting[['cuota_deposito', 'cuota_limpieza']].map(lambda x: x.replace('$','').replace(',','').strip()).astype(np.float64)

DataHosting.sample(3)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
1452,10.0,--,4,Enjoy the sunset from our sweet apartment over...,Our neighborhood is very centrally located. W...,1,1,1,Real Bed,"{TV,""Wireless Internet"",Kitchen,""Free Parking ...",0.0,0.0,138.0
3791,NaN,--,7,Brand new unobstructed 180 degree OCEAN VIEW h...,--,2,3,3,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",750.0,250.0,450.0
535,10.0,--,2,Lovely furnished bedroom private suite awaits...,We are located in West Seattle near Lincoln Pa...,1,1,1,Real Bed,"{""Cable TV"",Internet,""Wireless Internet"",Kitch...",100.0,35.0,87.0

## Datos de Texto

In [ ]:
# Realizar tokens de los textos ingresados en la aplicación

In [ ]:
# DataHosting['descripcion_local'] = DataHosting['descripcion_local'].str.lower()
DataHosting['descripcion_local'] = DataHosting['descripcion_local'].str.replace( '[^a-zA-Z0-9\-\']', ' ', regex=True)
DataHosting['descripcion_local'] = DataHosting['descripcion_local'].str.replace( '(?<!\w)-(?!\w)', ' ', regex=True)

In [ ]:
DataHosting['descripcion_local'].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one  convenientl...
4    the  studio at mibbett hollow' is in a beautif...
Name: descripcion_local, dtype: object

In [ ]:
DataHosting['descripcion_local'] = DataHosting['descripcion_local'].str.split()

In [ ]:
DataHosting['comodidades'] = DataHosting['comodidades'].str.replace( '\{|}|\"' , '', regex=True)

In [ ]:
DataHosting['comodidades'] = DataHosting['comodidades'].str.split(",")

In [ ]:
DataHosting['descripcion_vecindad'] = DataHosting['descripcion_vecindad'].str.replace( '[^a-zA-Z0-9\-\']', ' ', regex=True)
DataHosting['descripcion_vecindad'] = DataHosting['descripcion_vecindad'].str.replace( '(?<!\w)-(?!\w)', ' ', regex=True)
DataHosting['descripcion_vecindad'] = DataHosting['descripcion_vecindad'].str.split()
DataHosting['descripcion_vecindad']

0       [Lower, Queen, Anne, is, near, the, Seattle, C...
1       [Upper, Queen, Anne, is, a, really, pleasant, ...
2       [The, convenience, of, being, in, Seattle, but...
3       [Ballard, is, lovely, vibrant, and, one, of, t...
4                                                      []
                              ...
3813                                                   []
3814    [Quiet, dead, end, street, near, I-5, The, pro...
3815                                                   []
3816    [Your, hosts, made, Madison, Valley, their, ho...
3817    [Despite, the, quiet, leafy, streets, of, this...
Name: descripcion_vecindad, Length: 3818, dtype: object

## Datos de Fecha

In [ ]:
import datetime as dt

In [ ]:
dt.datetime.now()

datetime.datetime(2025, 7, 26, 15, 21, 5, 992938)

In [ ]:
dt.date.today()

datetime.date(2025, 7, 26)

In [ ]:
data_1 = dt.date(2022, 1, 1)
data_2 = dt.date(2025, 1, 1)

Difference = data_2 - data_1
Difference

datetime.timedelta(days=1096)

In [ ]:
DataInmuebles.head()

    id       fecha  lugar_disponible precio
0  857  2016-01-04             False   None
1  857  2016-01-05             False   None
2  857  2016-01-06             False   None
3  857  2016-01-07             False   None
4  857  2016-01-08             False   None

In [ ]:
DataInmuebles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            365000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB

In [ ]:
DataInmuebles['precio'] = DataInmuebles['precio'].fillna(0)
DataInmuebles['precio'] = DataInmuebles['precio'].apply(lambda x: x.replace('$','').replace(',','').strip() if isinstance(x, str) else x).astype(np.float64)
DataInmuebles['precio'].head(4)

0    0.0
1    0.0
2    0.0
3    0.0
Name: precio, dtype: float64

In [ ]:
DataInmuebles['fecha'] = pd.to_datetime(DataInmuebles['fecha'])

In [ ]:
DataInmuebles['fecha'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: fecha, Length: 365000, dtype: object

In [ ]:
DataInmuebles.groupby( DataInmuebles['fecha'].dt.strftime('%Y-%m') )['lugar_disponible'].sum()

fecha
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: lugar_disponible, dtype: int64

# DESAFIOS

In [ ]:
DataLocacao = pd.read_json('/content/drive/MyDrive/GoogleColab/dados_locacao_imoveis.json')
DataVentas = pd.read_json('/content/drive/MyDrive/GoogleColab/dados_vendas_clientes.json')

In [ ]:
DataLocacao = pd.json_normalize(DataLocacao['dados_locacao'])
DataLocacao.head(3)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"

In [ ]:
DataVentas = pd.json_normalize( DataVentas['dados_vendas'] )
DataVentas.head(3)

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"

In [ ]:
DataLocacao = DataLocacao.explode( ['datas_combinadas_pagamento',	'datas_de_pagamento',	'valor_aluguel'] )
DataLocacao.reset_index(inplace = True, drop = True)

DataVentas = DataVentas.explode( ['Cliente', 'Valor da compra'] )
DataLocacao.reset_index(inplace = True, drop = True)

In [ ]:
# DataLocacao['valor_aluguel'] = DataLocacao['valor_aluguel'].apply( lambda x: x.replace('$','').replace('reais','').replace(',','.').strip() ).astype(np.float16)

DataVentas['Valor da compra'] = DataVentas['Valor da compra'].apply( lambda x: x.replace('R','').replace('$','').replace(',','.').strip() ).astype(np.float16)

In [ ]:
DataLocacao['apartamento'] = DataLocacao['apartamento'].str.replace(" (blocoAP)","")

In [ ]:
DataVentas['Cliente'] = DataVentas['Cliente'].str.replace( '[^a-zA-Z\-\']', ' ', regex=True)
DataVentas['Cliente'] = DataVentas['Cliente'].str.replace( '(?<!\w)-(?!\w)', ' ', regex=True)
DataVentas['Cliente'] = DataVentas['Cliente'].str.lower()
DataVentas['Cliente']

0        ana  lucia
0    diego armandiu
0    diego armandiu
0    diego armandiu
1    isabely joanes
1    isabely joanes
1    isabely joanes
1    isabely joanes
2    isabely joanes
2      jo o gabriel
2    julya meireles
2    julya meireles
3    julya meireles
3       maria julia
3       maria julia
3       maria julia
4       maria julia
4       pedro pasco
4      paulo castro
4     thiago fritzz
Name: Cliente, dtype: object

In [ ]:
DataVentas['Data de venda'] = pd.to_datetime(DataVentas['Data de venda'], format='%d/%m/%Y')

In [ ]:
Total = DataVentas.groupby( ['Cliente'] )['Valor da compra'].sum()
Total

Cliente
 ana  lucia            836.500
diego armandiu        1478.750
isabely joanes        2329.625
jo o gabriel           386.250
julya meireles        1643.750
maria julia           2086.750
paulo castro           899.000
pedro pasco            311.250
thiago fritzz          885.000
Name: Valor da compra, dtype: float32

In [ ]:
DataLocacao.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022         2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022         1200.0

In [ ]:
DataVentas.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.50
0    06/06/2022  DieGO ARMANDIU 210           573.50
0    06/06/2022  DieGO ARMANDIU 210           392.75
0    06/06/2022  DieGO ARMANDIU 210           512.50
1    07/06/2022  Isabely JOanes 738           825.50

In [ ]:
DataLocacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float16
dtypes: float16(1), object(3)
memory usage: 912.0+ bytes

In [ ]:
DataVentas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float16
dtypes: datetime64[ns](1), float16(1), object(1)
memory usage: 1.1+ KB